### PR TITLE
Fixed flicking clock dial on Time Picker

### PR DESCRIPTION
**Pull request by yasincidem**
Overriding onInterceptTouchEvent method fixed flicking clock dial on Time Picker

### CODE REVIEW

**Review by coroutineDispatcher — COMMENTED** [review]
Hi, thank you for this tiny but important pull request.

My few cents here: Please name variables properly, mostly referring to `ev` for `MotionEvent` and `p` for `parent`. Also, I would not store it in a variable at all:

```
parent?. requestDisallowInterceptTouchEvent(true)
```

**Comment by yasincidem** [comment]
That totally makes sense. Fixed it

**Comment by coroutineDispatcher** [comment]
LGTM 👍  Thank you.

**Comment by KlausNie** [comment]
@yasincidem  Thank you very much for your contribution!

**Pull request merged**
